baseURL = "https://rubencosta13.github.io/website/"
canonifyURLs = false
relativeURLs = false
languageCode = "en"
defaultContentLanguage = "en"
title = "Ruben Costa"
theme = "PaperMod"
enableEmoji = true

[pagination]
pagerSize = 6

[taxonomies]
category = "categories"
tag = "tags"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[markup]
  [markup.highlight]
    noClasses = false
    style = "github"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
author = "Ruben Costa"
description = "Backend Developer • Computer Science Student • Erasmus+ Participant"
keywords = [
  "backend",
  "developer",
  "computer science",
  "erasmus",
  "portfolio"
]

dateFormat = "January 2, 2006"

defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
ShowWordCount = true

disableSpecial1stPost = true

[params.profileMode]
enabled = true
title = "Hi, I'm Ruben Costa!"
subtitle = """
Software Engineer

AI • Computer Vision • OCR • Distributed Systems • Backend Engineering
"""
imageUrl = "/images/profile.png"
imageTitle = "Ruben Costa"
imageWidth = 220
imageHeight = 220

[[params.socialIcons]]
name = "github"
url = "https://github.com/rubencosta13"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/rcosta13"

[[languages.en.menu.main]]
identifier = "erasmus"
name = "Erasmus"
url = "/erasmus/"
weight = 10

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20